### ISSUE TITLE
カテゴリの設定に使っている〝corder〟をテンプレートなどで使用したい

### ISSUE THREAD

**Issue by yotaca** [NucleusCMS/NucleusCMS-ja#117]
せっかく設定している、corder なので、加工してカテゴリの親子関係も持たせたい。
合わせて if文を整理したい。下記 Pullrequet で作成してみました。

https://github.com/yotaca/NucleusCMS-ja/pull/2

**Comment by yama** [comment]
https://github.com/NucleusCMS/NucleusCMS
もしよければ上記を使っていただけますでしょうか？
日本語版の機能はいったん全部巻き取ってあるので、同じように使えるはず。

**Comment by yotaca** [comment]
corder の番号が流れてくるだけではなく、corder の内容を使って 擬似的にカテゴリに〝親子関係〟をもたせたいんです。
当初はプラグインでコントロールしていましたが、それほど複雑な内容でもないので、BLOG.php の function showCategoryList に組み込みたいのですけどどうでしょう？

https://github.com/yotaca/NucleusCMS-ja/blob/admin01/nucleus/libs/BLOG.php
このファイルの800行目あたりです。

付随して プラグインで使っていたファンクションも増やしてますけど、追って整理します。
いかがでしょうか？

**Comment by yama** [comment]
corderについてはそれでいいと思いますが、日本語版は多数の不具合があるのを
あえて修正せずにそのままにしてます。それはよいでしょうか？

**Comment by yotaca** [comment]
そう考えるとちょっと使い辛いですね。
一旦オススメの方使っておきます。

ありがとうございました。

クローズしておきます。

**Comment by yotaca** [comment]
せっかくなんですけど、こちらは php3.7 mysql5.6 の環境でインストールできません。
https://github.com/NucleusCMS/NucleusCMS

DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci' at line 4

時間がないので、エラーがあるにしてもインストールできるこちらを使用することにします。
https://github.com/NucleusCMS/NucleusCMS-ja

気が付いたエラーは順次修正していきます。

**Comment by yotaca** [comment]
とりあえず Pullrequet 入れておきました。
https://github.com/NucleusCMS/NucleusCMS-ja/pull/118
