### ISSUE TITLE
bookmarklet.php の body と more の form に "submit" を入れると登録できない。

### ISSUE THREAD

**Issue by yotaca** [NucleusCMS/NucleusCMS-ja#119]
bookmarklet.php で form をアイテムとして登録、編集してボタンを設置する時、
`<input type="submit" value="申込み" name="submit">` と書くと『保存』できません。

どこかでチェックしていると思いますが、どこでチェックしているとは思いますが、チェックしている場所もわからないので、教えてもらえますか？

ちなみに、管理画面からアイテムを登録、編集する場合は、
`<input type="submit" value="申込み" name="submit">` と書いても『保存』できます。

**Comment by yama** [comment]
https://github.com/NucleusCMS/NucleusCMS
上記のほうはどうでしょうか？もし問題なければ参考にできると思います。
該当部分を特定するのが難しいかもですが、、

**Comment by yama** [comment]
何かエラーが表示されていたりはしますか？

**Comment by yotaca** [comment]
> https://github.com/NucleusCMS/NucleusCMS
> 上記のほうはどうでしょうか？もし問題なければ参考にできると思います。
> 該当部分を特定するのが難しいかもですが、、

こちらはインストールできないので、現在インストールしていません。
ただ、3.71 で動いているサイトでは submit と書かれていても登録できます。

> 何かエラーが表示されていたりはしますか？
エラー表示が出ていないので、おそらくJavascript でチェックしていると思います。
ここは jQuery などでチェックしているのでしょうか？

**Comment by yama** [comment]
特にチェックはしてないと思いますが、そういえば昔そんな話があったような
気がしないでもないような。
何らかの文字列に反応しているはずですが、それは特定できますか？

**Comment by yotaca** [comment]
> 特にチェックはしてないと思いますが、そういえば昔そんな話があったような
> 気がしないでもないような。
> 何らかの文字列に反応しているはずですが、それは特定できますか？

とりあえず『submit』です。

`<input type="submit" value="申込み" name="submit">`では登録できないのですが、
`<input type="" value="申込み" name="">`だったら登録できます。

**Comment by yotaca** [comment]
javascript のエラー画面に下記の通り表示されていました。
TypeError: document.editform.submit is not a function. (In 'document.editform.submit()', 
'document.editform.submit' is an instance of HTMLInputElement)

どうやら、name に submit を使ったのが原因のようです。

name="submit" の属性が 管理画面ではよくて、bookmarklet では ダメなのは釈然としませんが理由がわかったので、クローズしておきます。
