### ISSUE TITLE
Nucleus日本語サイトのMySQL接続エラー

### ISSUE THREAD

**Issue by torisanbird** [NucleusCMS/NucleusCMS-ja#129]
最近よくサイトがエラーになっているのを見かけます.

http://japan.nucleuscms.org/
  Could not connect to MySQL database.

http://japan.nucleuscms.org/forum/
  Unknown MySQL server host 'mysql5.sourceforge.jp' (111).

数年前にOSDNの運営会社がアピリッツに変更されていますから
機材入れ替えなどでMySQLサーバー認証でmysql5.sourceforge.jpがうまく引継ぎされていないのかもしれないです。

111は "Connection refused" らしいです。

現在の正式なドメイン名で接続したほうがいいと思います。

接続先のデータベースホスト名を変更する
mysql5.sourceforge.jp
↓
mysql5.osdn.jp

OSDN Docs (JP): MySQLデータベースの使い方
https://osdn.net/docs-ja/MySQL_Howto
データベースホスト: mysql5.osdn.jp

**Comment by osamuh** [comment]
ありがとうございます。

MySQLのホスト名を書き換えてみましたが、同じエラーが出ているようです。
osdn.net のシェルから直接 mysql --host=mysql5.sourceforge.jp や mysql --host=mysql5.osdn.jp でつなぐことはできているので、OSDN側の問題かもしれません。
問い合わせてみます。

**Comment by torisanbird** [comment]
ありがとうございました。

復旧を確認しましたので、クローズします。

**Comment by torisanbird** [comment]
深夜は表示されていたのですが
また表示されなくなっていますね

OSDN側での修復が終わるのを待つしかないですね
