### ISSUE TITLE
media upload disallowed/メディアアップロード許可されていません

### ISSUE THREAD

**Issue by MoFoQ** [NucleusCMS/NucleusCMS-ja#130]
v3.8-jaを使用。

メディアアップロード際にご覧のエラーが発生

"このアクションの実行が許可されていません。" (_ERROR_DISALLOWED, English "Sorry, you're not allowed to perform this action")

原因を探るとmedia.phpの中に$currentCollectionを確かめる部分があります。

media.php:
```
    // currently selected collection
    $currentCollection = requestVar('collection');
    if (!$currentCollection || !@is_dir($DIR_MEDIA . $currentCollection)) {
        $currentCollection = $member->getID();
    }

    // avoid directory travarsal and accessing invalid directory
    if (!MEDIA::isValidCollection($currentCollection)) {
        media_doError(_ERROR_DISALLOWED);
    }
```

MEDIA::isValidCollection()を見ると、stringとしてチェックされる。
libs/MEDIA.php:
```
        // allow creating new private directory
        if ($collectionName === (string)$member->getID()) {
            return true;
        }
```

そして、media.phpがMEDIA::isValidCollection()を呼ぶ前の$currentCollectionはstringでなくintであった（var_dumpで確認済みです）。

ご覧のように直しますた。
libs/MEDIA.php:
```
        // allow creating new private directory
        if ((string)$collectionName === (string)$member->getID()) {
            return true;
        }
```

media.phpの中で直すこともできますけどね。
```
    // currently selected collection
    $currentCollection = requestVar('collection');
    if (!$currentCollection || !@is_dir($DIR_MEDIA . $currentCollection)) {
        $currentCollection = $member->getID();
    }
   $currentCollection = (string) $currentCollection;
```
又は
```
    // avoid directory travarsal and accessing invalid directory
    if (!MEDIA::isValidCollection((string)$currentCollection)) {
        media_doError(_ERROR_DISALLOWED);
    }
```
---
(English)
I was getting an error when using the media upload feature: it would give "Sorry, you're not allowed to perform this action"

I was able to investigate and narrow down where it was having an issue.
In media.php, it would do a validation check which gets the $currentCollection.
When it fetches it, it gets returned as a int-type and in the validation check function in libs/MEDIA.php, it does an explicit comparison (aka, type-sensitive).
Fix can be made to libs/MEDIA.php OR in media.php (by typecasting it before calling the function)

**Comment by torisanbird** [comment]
NucleusCMS-ja/v3.8dev-ja の機能は NucleusCMS/v3.8dev に統合されていて

現在 v3.8dev-ja ブランチは メンテされていませんので、
開発版を使う場合は、NucleusCMS/v3.8dev を利用してください。


あと現在 日本ユーザーのみでメンテしていて
海外の開発者さんはいませんので、日本語だけで問題ないです。

**Comment by MoFoQ** [comment]
NucleusCMS/v3.8devのlibs/MEDIA.php (line 135)にはtypecastチェックがあるようですね　
```
        if (!is_string($collectionName)) {
            $collectionName = (string) $collectionName;
        }
        // allow creating new private directory
        if ($collectionName === (string)$member->getID()) {
            return true;
        }
```
